USE codeup_test_db;

INSERT INTO `albums` (artist_name, album_name, release_date, sales, genre)
      VALUES ('Michael Jackson', 'Thriller', '1982', '66', 'Pop'),
       ('Eagles', 'Their Greatest Hits', '1976', '51', 'Country'),
       ('AC/DC', 'Back in Black', '1980', '50', 'Hard Rock'),
       ('Pink Floyd', 'The Dark Side of the Moon', '1973', '45', 'Progressive Rock'),
       ('Meat Loaf', 'Bat Out of Hell', '1977', '43', 'Hard Rock'),
       ('Whitney Houston', 'The Bodyguard', '1992', '42', 'R&B'),
       ('Eagles', 'Hotel California', '1976', '42', 'Soft Rock'),
       ('Bee Gees', 'Saturday Night Fever', '1977', '40', 'Disco'),
       ('Fleetwood Mac', 'Rumours', '1977', '40', 'Soft Rock'),
       ('Various Artists', 'Grease: The Original Soundtrack', '1978', '38', 'Soundtrack'),
       ('Led Zeppelin', 'Led Zeppelin IV', '1971', '37', 'Hard Rock'),
       ('Michael Jackson', 'Bad', '1987', '35', 'Pop'),
       ('Alanis Morissette', 'Jagged Little Pill', '1995', '33', 'Alternative Rock'),
       ('Shania Twain', 'Come on Over', '1997', '33', 'Country'),
       ('Celine Dion', 'Falling into You', '1996', '32', 'Pop'),
       ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', '1967', '32', 'Rock'),
       ('Various Artists', 'Dirty Dancing', '1987', '32', 'Pop'),
       ('Michael Jackson', 'Dangerous', '1991', '32', 'Rock'),
       ('Adele', '21', '2011', '31', 'Pop'),
       ('Celine Dion', 'Lets''s Talk About Love', '1997', '31', 'Pop'),
       ('The Beatles', '1', '2000', '31', 'Rock'),
       ('ABBA', 'Gold: Greatest Hits', '1992', '30', 'Pop'),
       ('Madonna', 'The Immaculate Collection', '1990', '30', 'Pop'),
       ('The Beatles', 'Abbey Road', '1969', '30', 'Rock'),
       ('Bruce Springsteen', 'Born in the U.S.A', '1984', '30', 'Heartland Rock'),
       ('Dire Straits', 'Brothers in Arms', '1985', '30', 'Roots Rock'),
       ('James Horner', 'Titanic', '1997', '30', 'Soundtrack'),
       ('Metallica', 'Metallica', '1991', '30', 'Heavy Metal'),
       ('Nirvanna', 'Nevermind', '1991', '30', 'Grunge'),
       ('Pink Floyd', 'The Wall', '1979', '30', 'Progressive Rock'),
       ('Santana', 'Supernatural', '1999', '30', 'Latin Rock'),
       ('Guns N'' Roses', 'Appetite For Destruction', '1987', '30', 'Hard Rock');


